### PR TITLE
add manylinux2014 recipe

### PR DESCRIPTION
**Pull request by eugeneswalker**
Here is the updated manylinux2014 centos7 recipe with stipped out libcrypt.so per advice from @haampie

Retry of prior PR following https://github.com/spack/gitlab-runners/pull/57#issuecomment-2505498290
* https://github.com/spack/gitlab-runners/pull/57

### CODE REVIEW

**Comment by eugeneswalker** [comment]
Failing check here `Build pcluster-amazonlinux-2` seems unrelated to this PR.

**Comment by haampie** [comment]
I wouldn't call this manylinux, that's a python invention for centos with various pythons installed.

Many just centos 7 or linux-glibc2.17?

**Comment by eugeneswalker** [comment]
> Many just centos 7 or linux-glibc2.17?

Yes, I like this better

> Also it would be good to install an optimized python and prebuilt clingo binaries, otherwise every build job downloads clingo.
> 
> For example `clingo-bootstrap@spack +optimized ^python@3.11 +optimizations` like in https://github.com/spack/gitlab-runners/blob/main/spack.yaml

Good idea. I will update the recipe with this

**Comment by haampie** [comment]
Closing this in favor of #59

**Pull request closed without merging**
