### PR TITLE
Adding ParallelCluster configuration runner

### PR DESCRIPTION
**Pull request by stephenmsachs**
This runner builds GCC & OneApi compilers and will be used in CI stack `aws-pcluster` to build the packages defined in
https://github.com/spack/spack-configs/tree/main/AWS/parallelcluster.

### CODE REVIEW

**Review by eugeneswalker — DISMISSED** [review]

**Review by alalazo — COMMENTED** [review]
The recipe is very similar to `e4s-amazonlinux-2.dockerfile`. Is there any chance we can unify the two?

**Comment by eugeneswalker** [comment]
> The recipe is very similar to `e4s-amazonlinux-2.dockerfile`. Is there any chance we can unify the two?

I actually don't know why that recipe is labeled as `e4s` or where it came from. We don't use Amazon Linux 2 for any of our CI stacks. We also don't use the image generated by that recipe for anything. Do you know?

**Comment by alalazo** [comment]
@eugeneswalker I think it was added by @bollig last year in #3 to have pipelines for AWS (ISC and AHUG). The `e4s-` in the name is probably a cut and paste artifact.

**Comment by stephenmsachs** [comment]
> The recipe is very similar to `e4s-amazonlinux-2.dockerfile`. Is there any chance we can unify the two?

Going forward we should be able to use this instead of e4s-amazonlinux-2. It's a superset of that.

**Comment by alalazo** [comment]
@stephenmsachs So would it be good as a plan to:
1. Merge this one once CI is :heavy_check_mark: 
2. Confirm that this image works for your pipeline in a PR on spack/spack (using the tag `main` or `nightly`)
3. Confirm that this image works for the other AWS pipelines in the same PR on spack/spack 
4. Delete the `e4s-amazonlinux-2.dockerfile` recipe in this repo in another PR
5. Merge the PR at point 4, tag with a date
6. Update the PR in spack/spack, merge it

?

**Review by alalazo — APPROVED** [review]

**Pull request merged**
