### PR TITLE
Add `openssl` package to image

### PR DESCRIPTION
**Pull request by scottwittenburg**
This fixes a problem seen here:

https://gitlab.spack.io/spack/spack/-/jobs/6519254

### CODE REVIEW

**Comment by scottwittenburg** [comment]
fyi @adamjstewart

**Comment by scottwittenburg** [comment]
@alalazo @haampie Is it fine to use the system `openssl`?  Or should the problem be fixed another way?  Like maybe spack has a version we should use instead?

**Comment by haampie** [comment]
> This fixes a problem seen here:

Did you try it? It doesn't have any effect since it's in the wrong stage.

The thing you're linking points out that cargo fails to download something. I can download it fine with curl. Looks like the issue is with cargo not being able to locate certificates, so I would rather think it's a build issue, not an issue with the container.

**Comment by haampie** [comment]
My initial guess is rust builds cargo with vendored openssl that looks for system certs.

**Pull request closed without merging**
